// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/NewRange.tsx": () => import("../components/mockups/NewRange.tsx"),
  "./components/mockups/SauceTheCity.tsx": () => import("../components/mockups/SauceTheCity.tsx"),
  "./components/mockups/STC.tsx": () => import("../components/mockups/STC.tsx")
};
